repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.2
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy --config-file=pyproject.toml --strict --explicit-package-bases src
        language: system
        pass_filenames: false
        always_run: true
      - id: pytest-fast
        name: pytest-fast
        entry: uv run pytest -x --timeout=10 tests/ -m "not slow"
        language: system
        pass_filenames: false
        always_run: true
